name: Solar System Workflow

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: 'superuser'
  MONGO_PASSWORD: 'SuperPassword'
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        strategy:
          matrix:
            os: [ubuntu-latest,windows-server]
            version: [18,19,20]
        name: Unit Testing for OS ${{ matrix.os }}
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version ${{ matrix.version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.version}}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing first step1
          id: unit-test-result
          run: npm test
          continue-on-error: true

          
        - name: Archive Test Result
          if: steps.unit-test-result.outcome == 'failure'
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml